name: Despliegue automático a EC2

on:
  push:
    branches:
      - main  # Cambia si tu rama principal tiene otro nombre

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Desplegar en EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@100.26.213.92 << 'EOF'
            cd /home/ec2-user/distribuida
            git pull origin main

            # Matar cualquier proceso Flask previo (o Gunicorn si lo usas)
            pkill -f "flask run" || true

            # Lanzar Flask en segundo plano correctamente
            nohup flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
          EOF
          
